[package]
name = "pngme"
version = "0.1.0"
authors = ["Emiel Van Severen, <emiel@vanseveren.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]